INSERT INTO CALENDAR 
VALUES(CALBOARD_SEQ.NEXTVAL,'admin','일벙제목 테스트','일정 내용 테스트','202209261500',SYSDATE);

SELECT * FROM 
	CALENDAR c ;
	
SELECT * FROM USERINFO u ;

SELECT c.ID ,u.NAME ,c.CALTITLE ,c.CALCONTENT 
	FROM CALENDAR c ,USERINFO u 
	WHERE c.ID=u.ID;