
CREATE TABLE SCHEDULEBOARD(
	ID VARCHAR2(20),
	MANAGER VARCHAR2(10),
	FUNCTIONNAME VARCHAR2(50),
	STARTDATE DATE,
	ENDDATE DATE
);


CREATE SEQUENCE SCHEDULEBOARD_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO SCHEDULEBOARD(ID, MANAGER, FUNCTIONNAME, STARTDATE, ENDDATE)
	VALUES('GW'||SCHEDULEBOARD_SEQ.NEXTVAL, '김규철', '일정관리',
			TO_DATE('2022-05-10','YYYY-MM-DD'),TO_DATE('2022-05-14','YYYY-MM-DD'));

INSERT INTO SCHEDULEBOARD(ID, MANAGER, FUNCTIONNAME, STARTDATE, ENDDATE)
	VALUES('GW'||SCHEDULEBOARD_SEQ.NEXTVAL, '노수빈', '일정1',
			TO_DATE('2022-09-12','YYYY-MM-DD'),TO_DATE('2022-09-18','YYYY-MM-DD'));


SELECT ID, MANAGER, FUNCTIONNAME, TO_CHAR(STARTDATE, 'YYYY-MM-DD') AS STARTDATE, TO_CHAR(ENDDATE, 'YYYY-MM-DD') AS ENDDATE
FROM SCHEDULEBOARD;


---------------------------------------------------------------------------
SELECT * FROM CALBOARD c ;

CREATE TABLE CALBOARD(
	SEQ NUMBER NOT NULL ENABLE,
	ID VARCHAR2(20) NOT NULL ENABLE,
	TITLE VARCHAR(1000) NOT NULL ENABLE,
	CONTENT VARCHAR2(4000) NOT NULL ENABLE,
	MDATE VARCHAR2(12) NOT NULL ENABLE,
	REGDATE DATE NOT NULL ENABLE,
	CONSTRAINT CALBOARD_PK PRIMARY KEY ("SEQ")
);


------일정 추가 ---	
INSERT INTO CALBOARD 
		VALUES (
		CALBOARD_SEQ.NEXTVAL 
		,'hk'
		,'일정제목1'
		,'일정내용1'
		,'202209301055'
		,SYSDATE);
							
							
------일정 목록 조회 ---				
SELECT SEQ ,ID ,TITLE ,CONTENT ,MDATE ,REGDATE  
	FROM CALBOARD 
	WHERE ID='hk'
		AND SUBSTR(MDATE,1,8) ='20220921'
		ORDER BY MDATE;


------일정 상세 조회 --------
SELECT SEQ ,ID ,TITLE ,CONTENT ,MDATE ,REGDATE
	FROM CALBOARD WHERE SEQ = 0;


------일정 수정 --------
UPDATE  CALBOARD SET
		TITLE = '제목 수정',
		CONTENT = '내용 수정',
		MDATE = '202104081520',
		REGDATE = SYSDATE 
	WHERE SEQ ='21';
	

------일정 개수 구하기 --------
SELECT COUNT(*)
	FROM CALBOARD 
		WHERE ID = 'hk'
		AND SUBSTR(MDATE,1,8)='20220921';
	

------해당 달의 날마다 존재하는 일정의 개수를 3개까지 구하기 ------
SELECT SEQ ,ID ,TITLE ,CONTENT ,MDATE ,REGDATE
	FROM
		(SELECT ROW_NUMBER() OVER(PARTITION  BY SUBSTR(MDATE,1,8) ORDER BY MDATE) AS RN
				,SEQ 
				,ID 
				,TITLE 
				,CONTENT 
				,MDATE 
				,REGDATE
			FROM CALBOARD 
		WHERE ID = 'hk' AND SUBSTR(MDATE,1,6)='202209')
WHERE RN BETWEEN 1 AND 3;
	
	
	
------일정 글 삭제 -------
DELETE FROM CALBOARD
	WHERE SEQ IN (3,4,5,77,37);
